// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_stan_fit4gqs_loglik_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gqs_ppmc_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gqs_ppmc_probs_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gqs_probs_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4test_dina_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4gqs_loglik_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gqs_loglik_mod, 0},
    {"_rcpp_module_boot_stan_fit4gqs_ppmc_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gqs_ppmc_mod, 0},
    {"_rcpp_module_boot_stan_fit4gqs_ppmc_probs_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gqs_ppmc_probs_mod, 0},
    {"_rcpp_module_boot_stan_fit4gqs_probs_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gqs_probs_mod, 0},
    {"_rcpp_module_boot_stan_fit4test_dina_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4test_dina_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_measr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
